6 get/api/articles/article id/comments
Phil-Code/be-nc-news pull request #7
Opened 2023-10-03 13:50 UTC by Phil-Code

2023-10-03 14:53 UTC, NRMSMITH requested changes
Rewrite your first test for this endpoint - please resubmit once it's done 🚀

2023-10-03 14:53 UTC, NRMSMITH commented on __tests__/endpoints.test.js
> +        })
I think you should probably check that all the comments match the object -> so you need to have a look at a way of dynamically checking them all :) (a length check and then a forEach is probably the nicest way of doing it!)

2023-10-03 14:53 UTC, NRMSMITH commented on __tests__/endpoints.test.js
> +        })
👍

2023-10-03 14:53 UTC, NRMSMITH commented on __tests__/endpoints.test.js
> +        })
👍

2023-10-04 09:03 UTC, pippaamy approved these changes
great changes, go ahead and merge :)

2023-10-04 09:05 UTC, merged